version: "2.2"
services:
  irma01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: irma31
    environment:
      - node.name=irma01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=irma02,irma03
      - cluster.initial_master_nodes=irma01,irma02,irma03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    networks:
      - elastic
  irma02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: irma02
    environment:
      - node.name=irma02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=irma01,irma03
      - cluster.initial_master_nodes=irma01,irma02,irma03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
    networks:
      - elastic
  irma03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: irma03
    environment:
      - node.name=irma03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=irma01,irma02
      - cluster.initial_master_nodes=irma01,irma02,irma03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    ports:
      - 9203:9200
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge
